---
- hosts: master
  user: patmat
  sudo: true
  vars:
	  - db_name: mydb
	  - db_user: myuser
	  - db_host: localhost
	  - db_user_password: mypassword
	  - db_dump_file: /tmp/dump.sql.bz2
  roles:
	  - percona-cluster-role
